config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  # get 'help' => 'static_pages#help'
  get 'hakkinda' => 'static_pages#about'
  get 'iletisim' => 'static_pages#contact'
  get 'kayit' => 'users#new'


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name , presence: true, length: {minimum: 6, maximum:  50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
  validates :email , presence: true, length: {maximum: 255},
                     format: { with: VALID_EMAIL_REGEX },
                     uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    
  end

  def about
    
  end
  
  def contact
    
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="container">
      
  <div class="page-header">
    
    <ul class="nav nav-pills pull-right">
      <li role="presentation"><%= link_to "Ana Sayfa", root_path %> </li>
      <li role="presentation"><%= link_to "Profil", root_path %></li>
      <li role="presentation"><%= link_to "Kayit Ol", kayit_path %></li>
      <li role="presentation"><%= link_to "Hakkinda", hakkinda_path %></li>
      <li role="presentation"><%= link_to "İletisim", iletisim_path %></li>
    </ul>
    
    <h1>Example page header <small>Subtext for header</small></h1>
    
  </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    
    <%= render 'layouts/header' %>
    
    <div class="container">
      
      <%= yield %>
      
      
      <%= render 'layouts/footer' %>
      
    </div>
    
  
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>


<div class="welcome vertical-center">
  
  <h1>Bilgi deposu</h1>
  <h2>bilgi deposu.</h2>
  
  <%= link_to "Hemen üye ol.", "#", class: "btn btn-lg btn-primary" %>
  <%= link_to "yada giriş yap.", "#" %>
  

</div>

app/views/users/new.html.erb
<% provide(:title, "Yeni kayit") %>

<h1>Kayit Ol</h1>
<p>elelell</p>